### ISSUE TITLE
Improve GUI Styling

### ISSUE THREAD

**Issue by dr-rodriguez** [dr-rodriguez/MovingMast#14]
The GUI could use some button styling, and maybe some panel organization as some of them look like they are confined to narrow columns.
Exploring Panel's gridspec could be an option.

**Comment by malenarice** [comment]
I think I added it to the chain of a different pull request accidentally (#21), but I switched the GUI to be formatted with gridspec. Having trouble changing the colors of the buttons, but there should now be more flexibility in their format

**Comment by dr-rodriguez** [comment]
Yea I had a lot of trouble with the buttons, hence why I put this is a large issue. I did notice gridspec being used. 
I'll need to check out how it looks like.

**Comment by dr-rodriguez** [comment]
I've merged your pull, but commented out the gridspec use. It seems to add really large margins even after tweaking it a bit and doesn't solve the key issue which is that at startup the Tab part of the GUI is really narrow.

**Comment by dr-rodriguez** [comment]
Latest push forces a larger width to the individual tabs and this worked out well. Closing this issue for now.
