### ISSUE TITLE
Implement functions to check time step, date strings

### ISSUE THREAD

**Issue by dr-rodriguez** [dr-rodriguez/MovingMast#17]
Date strings and time step need a particular formats in the Horizons query. To avoid surprises we should implement a pair of functions that checks that the supplied string is indeed a date (eg, 2020-01-01) and that the time step supplied is valid (eg, 12h, 1d).
These functions should return True/False and would be used by the GUI and/or get_path functions to ensure valid inputs. A good place for them is in the target.py file

**Comment by masha-astro** [comment]
import time

def check(date):
    try:
      valid_date = time.strptime(date, '%Y-%m-%d')
    except ValueError:
        return False
    return True

**Comment by masha-astro** [comment]
https://pastebin.com/3Fy9U184
