### ISSUE TITLE
Fix panel deploy table issue

### ISSUE THREAD

**Issue by dr-rodriguez** [dr-rodriguez/MovingMast#20]
When deploying DemoInterface2.ipynb locally (via `panel serve --show DemoInterface2.ipynb` in a local Terminal) everything works, but the tables are missing some functionality. My guess is that there is an explicit extension we need to add to `pn.extensions()` as described in https://panel.holoviz.org/user_guide/Deploy_and_Export.html However, I don't know *which* one. Maybe a pandas related one?

**Comment by kortizceballos** [comment]
What functionality is missing? I tried importing all of the extensions listed in https://github.com/holoviz/panel/blob/04c73cae62b3e8775a44fd2373a55f8437901432/panel/config.py and the table looked the same to me before and after.
