### ISSUE TITLE
Request: usage commands in README

### ISSUE THREAD

**Issue by aimalz** [dr-rodriguez/MovingMast#27]
We'd like to build on what you've got in this repo for the [PLAsTiCC results visualization](https://github.com/aimalz/plasticc-explorer) hack, but your demo today went by a bit fast.  Would it be possible to add to this repo's README the commands that rendered the plots in a browser?  Thanks!

**Comment by dr-rodriguez** [comment]
I ran DemoInterface2.ipynb mainly on jupyter notebook.
To run in a website I ran `panel serve --show DemoInterface2.ipynb` on the command line. I'll add this to the README, but it's also listed in the notebook
